spring:
  application:
    name: embabel-agent-app
  profiles:
    active:
      - default
#      - tracing
  ai:
    openai:
      project-id: embabel
    mcp:
      client:
        enabled: true
        name: embabel
        version: 1.0.0
        request-timeout: 30s
        type: SYNC

        stdio:
          connections:
            time:
              command: docker
              args:
                - run
                - -i
                - --rm
                - mcp/time
                - --local-timezone=America/New_York
            firecrawl:
              command: docker
              args:
                - run
                - -i
                - --rm
                - -e
                - FIRECRAWL_API_KEY
                - mcp/firecrawl
              env:
                FIRECRAWL_API_KEY: ${FIRECRAWL_API_KEY}
presidio:
  analyzer:
    base-url: http://localhost:5002

embabel:
  agent:
    logging:
      personality: starwars
    platform:
      llm-operations:
        data-binding:
          max-attempts: 2
      ranking:
        llm: gpt-4.1-mini
  models:
    default-llm: gpt-4.1
  observability:
    enabled: false
    service-name: my-agent-app

management:
  langfuse:
    enabled: false
    endpoint: ${LANGFUSE_BASE_URL:}/api/public/otel
    public-key: ${LANGFUSE_PUBLIC_KEY}
    secret-key: ${LANGFUSE_SECRET_KEY}
    embabel-only: false

logging:
  level:
    com.embabel: INFO
    dev.jettro.blogpromotor: DEBUG

---
spring:
  config:
    activate:
      on-profile: tracing

embabel:
  observability:
    enabled: true

management:
  langfuse:
    enabled: true


