spring:
  ai:
    openai:
      project-id: embabel
    mcp:
      client:
        enabled: true
        name: embabel
        version: 1.0.0
        request-timeout: 30s
        type: SYNC

        stdio:
          connections:
            time:
              command: docker
              args:
                - run
                - -i
                - --rm
                - mcp/time
                - --local-timezone=America/New_York
            firecrawl:
              command: docker
              args:
                - run
                - -i
                - --rm
                - -e
                - FIRECRAWL_API_KEY
                - mcp/firecrawl
              env:
                FIRECRAWL_API_KEY: ${FIRECRAWL_API_KEY}
presidio:
  analyzer:
    base-url: http://localhost:5002
    pii-types: ["PERSON", "EMAIL_ADDRESS", "PHONE_NUMBER", "CREDIT_CARD_NUMBER"]

embabel:
  agent:
    logging:
      personality: starwars
    platform:
      llm-operations:
        data-binding:
          max-attempts: 2
      ranking:
        llm: gpt-4.1-mini
  models:
    default-llm: gpt-4.1

logging:
  level:
    com.embabel: INFO
    com.embabel.agent.api.annotation.support.AgentMetadataReader: INFO
    dev.jettro.blogpromotor: DEBUG


